export const state = {
    client: null,
    isConnected: false,
    connectionDebounce: null, 
    role: null,
    driverId: null,
    driverRoute: null,
    driverDestination: null,
    driverUsername: null,
    isBroadcasting: false,
    watchId: null,
    wakeLock: null,
    activeBuses: {},
    activeUsers: new Map(),
    userCache: {},
    map: null,
    driverMap: null,
    driverMarker: null,
    markers: {},
    circles: {}, 
    lastSentTime: 0,
    sessionPoints: 0,
    sessionDistance: 0,
    lastLat: null,
    lastLng: null,
    tripStartTime: null,
    uptimeInterval: null,
    currentSmoothedSpeed: 0
};
